### ISSUE TITLE
consistent member names

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/arbor#177]
The `struct` types are growing more complicated, and I find it confusing to understand what is local state and what is struct state.

A review of recent commits is needed, and some rules formalising the use of `struct` and associated member variable naming have to be written down.

**Comment by halfflat** [comment]
As a preliminary comment before a review, I'm in favour of having `struct` used over `class` when the member variables are public and read/writable with no or little private state. Mutable record-like aggregates would fall into this category.

If something is written up as a `struct`, then the public fields shouldn't (clearly, only IMO) be decorated with underscores or the like.

**Comment by halfflat** [comment]
I'm closing this because neither of us has had the will to engage with it.
