### ISSUE TITLE
Add (automated) documentation building to our builds

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/arbor#254]
This is one of those todo things that gets pushed backwards allot.

I have been looking at a couple of different engines and the choice is basically
1. Doxygen
2. Sphynx

These two are alive, have an active userbase and thus stackexchange. 
I worked with sphynx and I hate it. The documentation it produced is ugly 

Doxygen: http://eigen.tuxfamily.org/dox/group__TutorialAdvancedInitialization.html
sphynx: https://docs.python.org/2.7/library/stdtypes.html

I'm currently adding doxygen documentation to one of my personal projects and could probable port the stuff I learned easy to NestMC.

**Comment by w-klijn** [comment]
bcumming [3:11 PM] 
regarding autogen documentation, what are your plans there?
Because I have strong opinions about things like Doxygen that would require negotiation :wink: (edited)

w.klijn [3:14 PM] 
sphynx is ugly and I have bad experience.
doxygen looks nice and is the other of the two major players

bcumming [3:15 PM] 
For what it is worth: I think that Doxygen docstrings are a big hinderance to code readability.

w.klijn [3:15 PM] 
What do you propose?

bcumming [3:16 PM] 
I don't have any concrete proposals.
There will be parts of the library for which docstrings could be well justified, where we have a public API.

**Comment by w-klijn** [comment]
On a 'side' note. I'm putting on the table that I think documentation is a first class citizen for a successful project and expect to be writing a big part of it for NestMC.

**Comment by w-klijn** [comment]
Sooo. I have been looking for different c++ documentation generators:
Doc-O-Matic  :  payed
HeaderDoc: Last release 2009
Help Generator: Payed
ROBODoc: Last activity on github 2015
VSdocman: payed
DOC++: last release 2002
Imagix 4D: Payed
GenHelp Pro - FraserSoft:  payed
KDOC: The codebase is mostly orphaned now (from the homepage)
Twintext: The company writing it is dead
Universal Report: payed

The three viable options
1. Sphinx: Primary Python documentation, generates C++ documentation with Doxygen
2. Doxygen: defacto standard for C++ documentation generation
3. Reinvent the wheel:

**Comment by bcumming** [comment]
Doxygen is good at generating documentation of APIs from docstrings.
Does it also provide a nice way to do documentation that is not derived from the source code? Like Sphinx which lets you write generic documentation.
I would like to have seperate files where documentation about how to use the API is defined, along with detailed rationale behind design choices, and descriptions of algorithms etc.

**Comment by w-klijn** [comment]
Yes: create a directory (e.g. doc) and use it for standalone doxygen files. A standalone file is basically a text file consisting of only the C++ comment, e.g.:

http://entrenchant.blogspot.de/2009/09/doxygen-gotchas.html

**Comment by bcumming** [comment]
We have had automated generation of docs on Reathedocs via Sphinx since #328 

http://arbor.readthedocs.io/
