### ISSUE TITLE
Add stacktrace to exception handling

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/arbor#258]
When running a large application via a job scheduler a core dump is not always available (or even wanted). To help in debugging after the fact it would be handy to have a stack trace when an exception is throw.

Ben wrote code that produces stack traces.  and it is in NestMC.
We could override the behavior of `std::terminate` to produce a stack trace.

**Comment by w-klijn** [comment]
For the interested, I hunted for the implementation that was used in production at ASTRON.
This code was production hardened on BGQ, CUDA clusters.

[Backtrace.txt](https://github.com/eth-cscs/nestmc-proto/files/986693/Backtrace.txt)
[Exception.txt](https://github.com/eth-cscs/nestmc-proto/files/986692/Exception.txt)
[Backtrace.cc.txt](https://github.com/eth-cscs/nestmc-proto/files/986695/Backtrace.cc.txt)
[Exception_c.txt](https://github.com/eth-cscs/nestmc-proto/files/986696/Exception_c.txt)

**Comment by bcumming** [comment]
This is not trivial to implement properly. To do it properly, we need a backtrace generating code that is guarenteed not to throw, and we have the additional problem of handling potentially tens of thousands of MPI ranks generating stack traces.

I think that we need a very strong use case for this.

The solution from ASTRON is to use their own exception implementation, which records stack traces when thrown. This has two draw backs:
1. it generates the stack trace every time an exception is thrown.
2. if an exception that is not derived from their derived exception class, no back trace will be produced.

**Comment by bcumming** [comment]
This feature is not high priority, and we haven't really got a good use case for it, so I am closing it.
