### ISSUE TITLE
Implement custom transcendentals intrinsics

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/arbor#291]
We need to implement custom version of at least the following transcendentals:

- [x] `_mm256_exp_pd`
- [x] `_mm512_exp_pd`
- [x] `_mm256_log_pd`
- [x] `_mm512_log_pd`
- [x] `_mm256_pow_pd`
- [x] `_mm512_pow_pd`

In case we compile with a non-Intel compiler, we should use these custom intrinsics.

**Comment by bcumming** [comment]
Done in #450 !
