### ISSUE TITLE
Analysis/visualization of mini-app results

### ISSUE THREAD

**Issue by al-rigazzi** [eth-cscs/arbor#312]
Hi guys,

I ran the mini-app with "-p 1" and obtained a lot of json files as results. I was wondering if you have a tool to analyze/visualize them, or if you could point me to something.

Thanks,
Al

**Comment by halfflat** [comment]
Hi!

We do have a python script wrapping `matplotlib` that is designed to read in the time series geenrated by the miniapp (and validation tests) and plot them, on separate or combined plots.

The script is in `scripts/tsplot`, and while `--help` gives an option summary, there is more information in `scripts/README.md`.

**Comment by al-rigazzi** [comment]
Thank you!

I will look into `scripts`!

**Comment by halfflat** [comment]
I'm going to close this issue, but let us know if the `tsplot` script and such are unsuitable!
