### ISSUE TITLE
MPI world behaviour review

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/arbor#313]
Nest has a hard time communication via MPI to other application because it makes assumptions regarding WORLD and its usage of it.

We should review our usage and prevent the same mistakes.

**Comment by bcumming** [comment]
Agreed.
We need to make the communication policy run-time configurable, and creating an MPI based communicator with a user-supplied MPI_Communicator would be an option.

**Comment by bcumming** [comment]
See #472.
