### ISSUE TITLE
Issues with CMake vs TBB vs HPC systems.

### ISSUE THREAD

**Issue by halfflat** [eth-cscs/arbor#332]
PR #331 uses a new mechanism for building and linking against TBB. While it solves the build problem for now, there are some deficiencies in the approach which are hard to address, thanks to the combination of CMake generally and TBB inflexibility regarding linking in particular:
  1. The build now requires that the TBB source package be downloaded at configure time, but unrestricted access to the Internet is not always possible on HPC systems.
  2. The forced dynamic linking adds a requirement that the build filesystem and directory be accessible from the execution environment, which again is not guaranteed in systems with separate front end machines and compute nodes.
  3. There is no way currently to instruct the build to use a specific version of TBB that may already be installed or customized for the environment.
  3. It adds a bunch of TBB boilerplate CMake code to the project, which is broadly undesirable.

In principle these can be addressed by spending enough time dicking about with CMake scripts and TBB's `make`-based build process.

**Comment by bcumming** [comment]
I am leaning towards the following solution

  1. Have a Git submodule point to the main TBB repository at github.com/01org/tbb
  2. Write our own CMakeLists.txt that builds TBB as a static library
  3. Have CMake copy this CMakeLists into the submodule path and build if the TBB back end is chosen by the user.

The Makefile and associated system/compiler specific settings used by TBB are clear enough that this shouldn't be too hard.
