### ISSUE TITLE
Migrate to C++14 [4]

### ISSUE THREAD

**Issue by halfflat** [eth-cscs/arbor#358]
Moving to C++14 for the (non-kernel) sources will allow us to remove a number of work-arounds in the code (e.g. the `DEDUCED_RETURN_TYPE` macro and the lack of aggregate initializations for PODs with default value) and simplify a bunch of the type-wrangling currently performed.

We can _probably_ assume that a sufficiently capable C++14 compiler exists on our target platforms.

Tasks:
1. Try it! Use C++14 as the language for compilation, and see what breaks, on various platforms.
2. Simplify code using the existing we're-not-using-C++14-yet work-arounds.

**Comment by bcumming** [comment]
This would need defining what our minimum versions are, e.g. gcc 5.2 and clang 3.x.

**Comment by halfflat** [comment]
Key things to test:
* How to negotiate setting `-std=c++14` against `nvcc` options within CMake?
* Confirm a recent `icpc` supports: deduced return types; aggregate initialization of structs with default member values; template variables; `std::enable_if_t` and friends.

**Comment by bcumming** [comment]
Add the following feature for testing:
  * generic lambdas

Remove the following:
  * `util::make_unique`
