### ISSUE TITLE
Fix CUDA 9 warp intrinsics warnings

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/arbor#379]
CUDA 9 introduced more sophisticated warp-level synchronization. Intrinsics like `__ballot` and `__shfl` were depricated to be replaced with more specific instructions like `__shfl_sync`.

We are getting warnings with CUDA 9, e.g.
```
/users/bcumming/repos/arbor/src/backends/gpu/kernels/reduce_by_key.hpp(92):
  warning: function "__ballot"
/cm/shared/apps/cuda-9.0/include/sm_20_intrinsics.h(407):
  here was declared deprecated ("__ballot() is deprecated in favor of __ballot_sync()
  and may be removed in a future release (Use -Wno-deprecated-declarations to suppress
  this warning).")
```

**Comment by AndiH** [comment]
Just to put this somewhere – I don't know if it actually applies to your code: Be sure that the warp-based code uses proper warp-level synchronization (that is: explicit synchronization and not implicit; `__syncwarp`). With Volta, threads can be scheduled individually (warp-independently). Some hints here https://devblogs.nvidia.com/parallelforall/inside-volta/

**Comment by bcumming** [comment]
Thanks @AndH. This might actually be the case for the reduce by key code. I will look into it.
