### ISSUE TITLE
Fix reproducibility by sorting events first by time then by weights

### ISSUE THREAD

**Issue by kabicm** [eth-cscs/arbor#385]
In case two events have exactly the same time (which can happen when a very large number of events is produced), there is an ambiguity in the order in which such events are processed which might result in different numberical results when the same simulation is repeated.

To ensure that the order of operations is deterministic, the events that happened at the same time should further be sorted by their weights.

**Comment by bcumming** [comment]
Thanks for all your work in finding this problem!

I will make sure that this is fixed when I refactor the event-wrangling code to remove it from cell_groups in #378. That way the logic will be available to all cell_group implementations.

**Comment by kabicm** [comment]
Thank you and Sam for the help and brainstorming!
