### ISSUE TITLE
Setting temperature in model

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/arbor#386]
The temperature is currently hard coded at 6.3 degrees celcius (279.45 Kelvin).

When the mechanism interface and parameter setting work described in has been finished in #365 and #349, this can be tackled fairly easily.

**Comment by halfflat** [comment]
This is now implemented as a field in `mc_cell_global_properties` for the purpose of Nernst calculations. It's _not_ propagated through the NMODL magic `celsius` parameter yet.

**Comment by halfflat** [comment]
Started an approach to have `celsius` be magic in NMODL, and link it up with a special scalar external data source, but it's pretty invasive (and doesn't work yet).

Simpler solution is to have special-case handling for a global parameter called `celsius` in `fvm_lowered_impl::reset()`. Less invasive, but also much hackier — it treads all over the existing mechanism specialization semantics for global scalar parameters.

**Comment by halfflat** [comment]
Without deeply messing with the way procedures are handled (it's particularly a problem for SIMD printing), the 'clean' way looks like:
* A parameter `celsius` is recognized as an externally-backed indexed variable (but not a range variable unless we want to add that functionality later).
* No longer being a true parameter, using `celsius` in an NMODL procedure requires passing it in as an argument.

It involves making further restrictions on the NMODL we accept, but the alternatives to this are either very hacky or very invasive. This is currently the approach I will take to a PR.
