### ISSUE TITLE
Restructure miniapp directory

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/arbor#403]
We should have a `miniapps` (or other similar name) directory for demo/miniapp codes, and move our current `miniapp` into that, pending a further subdivision of its capabilities

1) renaming the current miniapp path to miniapps
2) moving the current miniapp into a subdirectory (what to call it, `mc_ball_of_tar`?)
3) updating the CMakeLists.txt to find the miniapp
4) updating the travis script to find the miniapp in its new location

**Comment by bcumming** [comment]
This was performed a while back in PR #423.
