### ISSUE TITLE
Arbor fails to compile with AVX2 backend

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/arbor#407]
There seems to be a regression in the compilation using the AVX2 backend:

```
cmake -DARB_SYSTEM_TYPE=Cray -DARB_WITH_PROFILING=ON -DARB_WITH_ASSERTIONS=ON -DARB_VECTORIZE_TARGET=AVX2 ~/Devel/arbor/
make
```

Output:
```
[ 16%] Building CXX object src/CMakeFiles/arbor.dir/backends/multicore/fvm.cpp.o
In file included from /users/karakasv/Devel/arbor/src/backends/multicore/fvm.cpp:3:0:
/users/karakasv/Devel/arbor/mechanisms/multicore/hh_cpu.hpp: In member function 'void arb::multicore::mechanism_hh<Backend>::rates(int, __m256d)':
/users/karakasv/Devel/arbor/mechanisms/multicore/hh_cpu.hpp:329:34: error: cannot convert '__m256d {aka __vector(4) double}' to 'double' for argument '1' to 'double exp(double)'
         ll0_ = ll2_/(exp(ll2_/ 10)- 1);
                                  ^
```

I am testing on Dom with gcc 7.1.

It seems that vectorized output is mixed with standard library calls and standard types.

**Comment by vkarak** [comment]
I think the problem comes from the `CExprEmitter`.

**Comment by vkarak** [comment]
It seems like the `SimdPrinter` must inherit from `CExprEmitter`.

**Comment by halfflat** [comment]
If you like, I can look after this one. I expect a good solution would be to have, distinct from the SimdPrinter, a simd-specific class that acts like CExprEmiiter does for the C and CUDA printers.

**Comment by vkarak** [comment]
> If you like, I can look after this one. 

That's fine, I'm on it.

My previous statement about the `SimdPrinter` and the `CExprEmitter` was wrong. Now, I see what you are doing, that is, using `CExprEmitter` as a backend of the CPrinter, so the design you propose is reasonable and will integrate better the `SimdPrinter` to the refactored infrastructure. For the moment, I need to track down what exactly triggers the `CExprEmitter`, 'cause `SimdPrinter` implements the methods that are supposed to be called. I may submit just a bugfix before going through refactoring of `SimdPrinter`.
