### ISSUE TITLE
Developer documentation?

### ISSUE THREAD

**Issue by mananatee** [eth-cscs/arbor#416]
Hi there, 

I'd be interested in contributing to the development of arbor, even if it's only on small things. 

Is there an entry point for new developers besides the 'Wiki' tab? Anything about software architecture, maybe references to algorithms that are used? Anything would be welcome. I'd even be happy to organize some documentation somewhere.

Cheers,
Lucas.

**Comment by bcumming** [comment]
Hello Lucas.

You are very welcome to contribute. Unfortunately we don't have much documentation.

We have set up some Read the docs 
http://arbor.readthedocs.io/en/latest/
But there is very little there.

Arbor will be "released" in March 2018, which is when we aim to have improved documentation.

So, because I don't have much documentation to point you towards, the best spot to start might be for you to let us know what you want to do with Arbor and/or what sort of contribution you want to make?

**Comment by mananatee** [comment]
Hi Ben, 

I'm running simulations of networks of neurons in the basal ganglia for my PhD research, currently using NEURON, recently starting in a cluster environment. We plan to scale this up to larger networks so will need a fast simulator, and since I have a CS background I'm naturally interested in the implementation-side of this too. I'm keen on understanding the ins and outs of a modern compartmental simulator basically: everything from the cable equation to an efficient vectorized implementation (I like to understand my tools). I got started with NEURON and read some of the implementation papers, but the code is a bit too convoluted and undocumented at this point imo.

I could contribute wherever is needed, mainly as a personal incentive to better understand the inner workings but would be great to help bring the project forward in any way.

All the best,
Lucas.

**Comment by bcumming** [comment]
Lucas, it sounds like you are the ideal early user. As long as you are happy to work with us on code that is still in early development, your contribution is welcome.

We aim to be modern, both in the sense of having a sane and extensible design, and in terms of running on modern architectures like GPUs and multi/many-core vectorized CPUs.

You can send me an email at bcumming@cscs.ch, and I can add you to our Slack team, where we can discuss in more detail how you could get started.

**Comment by mananatee** [comment]
I think this can be closed. I'll leave some useful links here for people with the same question:

- The official documentation is [here](http://arbor.readthedocs.io/en/latest/index.html), it includes a 'Developers' section although that is limited in scope at the moment.
- The repo's [wiki pages](https://github.com/eth-cscs/arbor/wiki) have some information that could be useful to potential developers
- contact the repo's administrators for specific queries
