### ISSUE TITLE
What dimensions do we want to explore during the BGQ bigscaling week?

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/arbor#433]
We have discussed about this shortly before, but I would like to get your inputs regarding the experiments we need to perform and make these explicit so we don't have any tears after the fact. 
Dimensions I see:
1. Number of neurons
2. Number of dendrite segments
3. Number of synapses
4. HH vs passive dendrite dynamics
5. Fraction shortrange vs longrange (small-world) connections
6. Average spike rate (This is a hard Dimension and might not be very controllable)
x. Anything you come up with

I want to put some numbers on these dimensions and what combinations you guys would like to see.

**Comment by w-klijn** [comment]
bcumming [5:25 PM] 
On point 6. I think that we are more interested in spiking patters. i.e. our current miniapp produces the near-perfectly synchronized spike chains, which just sucks.


[5:26] 
Having different spiking patterns to test the communication would be nice (i.e. synchronized etc).


w.klijn [5:42 PM] 
eerhm, spike patterns are emergent behavior of the network and thus hard to control. We might be able to do some thing with the Inhomogeneous Spike Source. Even for this situation the actual spikes as produced by the network are not under full control.


[5:43] 
It might just be better to use a very large number of synthetic spike sources of you want this high amount of control over the spikes in the communication

**Comment by bcumming** [comment]
We are most interested in the performance wins and losses that you have running what you think is an interesting workload. I could come up with a list of features that I want benchmarked, but I am not a neuroscientist or user, so I don't know how much optimizing my benchmarks would help "real world" users.

**Comment by apeyser** [comment]
Spike frequencies would be interesting, since our miniapp gives us only a high frequency * a low frequency, more randomized but drivable would let us see what the limits on the system are.

We have the fan parameter to check -- so number of synapses per neuron, plus the complexity of the neurons themselves. The number of neurons is probably fixable to what fills memory.

**Comment by w-klijn** [comment]
@bcumming I would be interested in that list. I am interested in all viewpoints. This is a benchmark network we are going to run: Explicitly NOT a biophysically fully constraint network.

**Comment by bcumming** [comment]
The scaling week is over, so I will go ahead and close this.
