### ISSUE TITLE
Move `spike_source_cell` into seperate header

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/arbor#499]
So that the recipe/user facing code is not exposed cell group guff.

**Comment by halfflat** [comment]
I've done the split in the work-in-progress installable target task.

**Comment by bcumming** [comment]
It is in the PR for the benchmark cell.

**Comment by halfflat** [comment]
o no! merge conflict!
I kid.

**Comment by halfflat** [comment]
Resolved.
