### ISSUE TITLE
Clang fails to compile the vectorized backends

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/arbor#587]
I have tried using Clang 6.0.1. This is the build script I use:

```
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DARB_WITH_ASSERTIONS=ON -DARB_VECTORIZE=ON #-DARB_ARCH=native
make -j
```

I have tried also enabling the ARB_ARCH variable, but again fails. The errors I am getting are of several kinds. Here are some of them:

```
mechanisms/generated/kdrmt_cpu.cpp:118:20: error: no matching constructor for initialization of 'arb::simd_value' (aka 'arb::simd::simd_detail::simd_impl<void>')

arbor/simd/simd.hpp:106:50: error: array has incomplete element type 'const arb::simd::simd_detail::simd_impl<void>::scalar_type' (aka 'const void')

etc.
```
Same behaviour with AppleClang 9.1.0.
Non-vectorized version compiles fine.

**Comment by halfflat** [comment]
I'm not getting the error if I set `ARB_ARCH` to an architecture for which we have a SIMD implementation: do you get the same errors in that circumstance?

We certainly could do with a test or better error for the case where vectorization is requested but we do not have an implementation.
