### ISSUE TITLE
modcc silently ignores invalid target file

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/arbor#79]
If modcc is given an invalid file name, e.g.
```
modcc -t cpu -o kernels/hh.hpp hh.mod
```
where the path `kernels` doesn't exist, it prints a message to the effect that it successfully compiled the file, when in fact the file `kernels/hh.hpp` was never created.

* an error message should be printed
* a non-zero value returned to the shell so that CMake is alerted to the error

**Comment by halfflat** [comment]
This was fixed along the way when `modcc.cpp` and the bulkio code was rejigged.
